name: Trigger ZLUX Core Build

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - v3.x/staging

permissions:
  contents: write

jobs:
  build-core:
    uses: zowe/zlux-build/.github/workflows/build-core.yml@v3.x/staging
    secrets: inherit
    with:
      SOURCE_REPO: zlux-app-server
      SOURCE_PR: ${{ github.event.pull_request.number || '' }}

      ZLUX_APP_SERVER: ${{ github.event.pull_request.number || '' }}
